### #0 Import dependencies

In [17]:
import numpy as np
import gym

### #1 Create Environment

In [18]:
env = gym.make('Taxi-v2')
env.render()

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



### #2 Create Q-table and initialize it 

In [19]:
action_size = env.action_space.n
print(f"Action size is {action_size}")

state_size = env.observation_space.n
print(f"State size is {state_size}")

Action size is 6
State size is 500


#### Here 6 actions are:
- up
- down
- right
- left
- pick-up
- deliver

#### There are 500 (25 x 5 x 4) possible states:
- 25 squares
- 5 locations for the passenger (counting the four starting locations - R, G, Y, B - and the taxi)
- 4 destinations

In [20]:
qTable = np.zeros((state_size, action_size))  # Initializing to zero
print(qTable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### #3 Specify hyperparameters 

In [21]:
total_eps = 50000
total_test_eps = 100
max_steps = 99                     # Max steps per ep

lr = 0.7                           # Learning Rate
gamma = 0.618                      # Discounting rate

# Exploration Parameter
epsilon = 1                        # Exploration rate
max_epsilon = 1                    # Exploration probability at start
min_epsilon = 0.01                 # Minimum exploration probability
decay_rate = 0.01                  # exp decay of exploration probability

### #4 Q-learning algorithm 

In [22]:
for ep in range(total_eps):
    
    # Reset the state
    state = env.reset()
    step = 0
    done = False
    
    for step in range(max_steps):
        tradeoff = np.random.uniform(0, 1)
        
        if tradeoff > epsilon:
            # Select the one with maximum Q-value ---> exploitation
            action = np.argmax(qTable[state, :])
        else:
            # Random action ---> exploration
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-value using Bellman equation
        qTable[state, action] += lr * (reward + (gamma * np.max(qTable[new_state, :])) - qTable[state, action])
        
        state = new_state
        
        if done == True:
            break
    ep += 1
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(- decay_rate * ep)

### #5 Use Q-Table to play Taxi 

In [16]:
rewards = []

for ep in range(total_test_eps):
    state = env.reset()
    step = 0
    done = False
    total_reward = 0
    
    print("*" * 30)
    print(f"Episode: {ep}")
    
    for step in range(max_steps):
        env.render()
        action = np.argmax(qTable[state, :])
        
        new_state, reward, done, info = env.step(action)
        total_reward += reward
        
        if done:
            rewards.append(total_reward)
            print(f"Score: {total_reward}")
            break
        state = new_state
env.close()
print("Score over time: ", sum(rewards) / total_test_eps)

******************************
Episode: 0
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (West)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R:_| : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| :_: : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : :_: : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : :_: |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | :_:G|
| : : :

Episode: 69
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (East)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Pickup)
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : |_: |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : : : |
| : : :_: |
| | : | : |
|Y| : |B: |
+---------+
  (North)
+---------+
|R: | : :G|
| : : :_: |
| : : : : |
| | : | : |